export const INITIAL_ACHIEVEMENTS = [
  // Onboarding
  {
    key: "welcome",
    name: "Welcome!",
    description: "Set your alias for the first time",
    icon: "👋",
    tier: null,
    category: "onboarding",
    xpReward: 25,
    criteria: { type: "count", action: "alias:set", threshold: 1 },
    sortOrder: 1,
  },
  {
    key: "surveyor",
    name: "Have Your Say",
    description: "Complete the community survey",
    icon: "📋",
    tier: null,
    category: "onboarding",
    xpReward: 50,
    criteria: { type: "count", action: "survey:complete", threshold: 1 },
    sortOrder: 2,
  },

  // Content — Posts (tiered)
  {
    key: "writer_bronze",
    name: "Writer",
    description: "Create 5 posts",
    icon: "✏️",
    tier: "bronze",
    category: "content",
    xpReward: 50,
    criteria: { type: "count", action: "post:create", threshold: 5 },
    sortOrder: 10,
  },
  {
    key: "writer_silver",
    name: "Author",
    description: "Create 15 posts",
    icon: "✏️",
    tier: "silver",
    category: "content",
    xpReward: 100,
    criteria: { type: "count", action: "post:create", threshold: 15 },
    sortOrder: 11,
  },
  {
    key: "writer_gold",
    name: "Prolific Writer",
    description: "Create 50 posts",
    icon: "✏️",
    tier: "gold",
    category: "content",
    xpReward: 250,
    criteria: { type: "count", action: "post:create", threshold: 50 },
    sortOrder: 12,
  },
  {
    key: "writer_legendary",
    name: "Literary Legend",
    description: "Create 100 posts",
    icon: "✏️",
    tier: "legendary",
    category: "content",
    xpReward: 500,
    criteria: { type: "count", action: "post:create", threshold: 100 },
    sortOrder: 13,
  },

  // Content — Comments (tiered)
  {
    key: "commenter_bronze",
    name: "Commenter",
    description: "Write 10 comments",
    icon: "💬",
    tier: "bronze",
    category: "content",
    xpReward: 50,
    criteria: { type: "count", action: "thread:create", threshold: 10 },
    sortOrder: 20,
  },
  {
    key: "commenter_silver",
    name: "Conversationalist",
    description: "Write 50 comments",
    icon: "💬",
    tier: "silver",
    category: "content",
    xpReward: 100,
    criteria: { type: "count", action: "thread:create", threshold: 50 },
    sortOrder: 21,
  },
  {
    key: "commenter_gold",
    name: "Discussion Leader",
    description: "Write 100 comments",
    icon: "💬",
    tier: "gold",
    category: "content",
    xpReward: 250,
    criteria: { type: "count", action: "thread:create", threshold: 100 },
    sortOrder: 22,
  },
  {
    key: "commenter_legendary",
    name: "Voice of the Community",
    description: "Write 500 comments",
    icon: "💬",
    tier: "legendary",
    category: "content",
    xpReward: 500,
    criteria: { type: "count", action: "thread:create", threshold: 500 },
    sortOrder: 23,
  },

  // Social — Shouts (tiered)
  {
    key: "shouter_bronze",
    name: "Loud & Proud",
    description: "Send 25 shouts",
    icon: "📢",
    tier: "bronze",
    category: "social",
    xpReward: 50,
    criteria: { type: "count", action: "shout:create", threshold: 25 },
    sortOrder: 30,
  },
  {
    key: "shouter_silver",
    name: "Town Crier",
    description: "Send 100 shouts",
    icon: "📢",
    tier: "silver",
    category: "social",
    xpReward: 100,
    criteria: { type: "count", action: "shout:create", threshold: 100 },
    sortOrder: 31,
  },
  {
    key: "shouter_gold",
    name: "Megaphone",
    description: "Send 500 shouts",
    icon: "📢",
    tier: "gold",
    category: "social",
    xpReward: 250,
    criteria: { type: "count", action: "shout:create", threshold: 500 },
    sortOrder: 32,
  },

  // Moderation
  {
    key: "bug_hunter_bronze",
    name: "Bug Hunter",
    description: "Report your first issue",
    icon: "🐛",
    tier: "bronze",
    category: "moderation",
    xpReward: 30,
    criteria: { type: "count", action: "issue:create", threshold: 1 },
    sortOrder: 40,
  },
  {
    key: "bug_hunter_silver",
    name: "Quality Guardian",
    description: "Report 5 issues",
    icon: "🐛",
    tier: "silver",
    category: "moderation",
    xpReward: 75,
    criteria: { type: "count", action: "issue:create", threshold: 5 },
    sortOrder: 41,
  },
  {
    key: "bug_hunter_gold",
    name: "Bug Exterminator",
    description: "Report 15 issues",
    icon: "🐛",
    tier: "gold",
    category: "moderation",
    xpReward: 150,
    criteria: { type: "count", action: "issue:create", threshold: 15 },
    sortOrder: 42,
  },

  // Calendar events
  {
    key: "organizer_bronze",
    name: "Event Organizer",
    description: "Create your first event",
    icon: "📅",
    tier: "bronze",
    category: "content",
    xpReward: 30,
    criteria: { type: "count", action: "event:create", threshold: 1 },
    sortOrder: 50,
  },
  {
    key: "organizer_silver",
    name: "Party Planner",
    description: "Create 5 events",
    icon: "📅",
    tier: "silver",
    category: "content",
    xpReward: 75,
    criteria: { type: "count", action: "event:create", threshold: 5 },
    sortOrder: 51,
  },

  // Forum topics
  {
    key: "topic_starter_bronze",
    name: "Topic Starter",
    description: "Create your first forum topic",
    icon: "🎯",
    tier: "bronze",
    category: "content",
    xpReward: 30,
    criteria: { type: "count", action: "topic:create", threshold: 1 },
    sortOrder: 60,
  },
  {
    key: "topic_starter_silver",
    name: "Forum Regular",
    description: "Create 10 forum topics",
    icon: "🎯",
    tier: "silver",
    category: "content",
    xpReward: 100,
    criteria: { type: "count", action: "topic:create", threshold: 10 },
    sortOrder: 61,
  },

  // Streak achievements
  {
    key: "streak_bronze",
    name: "Dedicated",
    description: "7-day login streak",
    icon: "🔥",
    tier: "bronze",
    category: "social",
    xpReward: 75,
    criteria: { type: "count", action: "login:streak", threshold: 7 },
    sortOrder: 70,
  },
  {
    key: "streak_silver",
    name: "Committed",
    description: "30-day login streak",
    icon: "🔥",
    tier: "silver",
    category: "social",
    xpReward: 200,
    criteria: { type: "count", action: "login:streak", threshold: 30 },
    sortOrder: 71,
  },
  {
    key: "streak_gold",
    name: "Unstoppable",
    description: "90-day login streak",
    icon: "🔥",
    tier: "gold",
    category: "social",
    xpReward: 500,
    criteria: { type: "count", action: "login:streak", threshold: 90 },
    sortOrder: 72,
  },
  {
    key: "streak_legendary",
    name: "Eternal Flame",
    description: "365-day login streak",
    icon: "🔥",
    tier: "legendary",
    category: "social",
    xpReward: 1000,
    criteria: { type: "count", action: "login:streak", threshold: 365 },
    sortOrder: 73,
  },

  // Tutorial achievements
  {
    key: "quick_learner",
    name: "Quick Learner",
    description: "Complete all tutorial steps available for your role",
    icon: "🎓",
    tier: null,
    category: "onboarding",
    xpReward: 100,
    criteria: { type: "count", action: "tour:step", threshold: 10 },
    sortOrder: 80,
  },
  {
    key: "tour_guide",
    name: "Tour Guide",
    description: "Complete all 17 tutorial steps",
    icon: "🗺️",
    tier: "legendary",
    category: "onboarding",
    xpReward: 500,
    criteria: { type: "count", action: "tour:step", threshold: 17 },
    sortOrder: 81,
  },
];

export const INITIAL_QUESTS = [
  // Onboarding (one-time)
  {
    key: "onboarding_alias",
    name: "Identity Crisis",
    description: "Set your community alias",
    icon: "🏷️",
    type: "onboarding",
    xpReward: 25,
    criteria: { action: "alias:set", count: 1 },
    repeatable: false,
    sortOrder: 1,
  },
  {
    key: "onboarding_survey",
    name: "Have Your Say",
    description: "Complete the community survey",
    icon: "📋",
    type: "onboarding",
    xpReward: 100,
    criteria: { action: "survey:complete", count: 1 },
    repeatable: false,
    sortOrder: 2,
  },
  {
    key: "onboarding_first_shout",
    name: "First Words",
    description: "Send your first shout",
    icon: "📢",
    type: "onboarding",
    xpReward: 25,
    criteria: { action: "shout:create", count: 1 },
    repeatable: false,
    sortOrder: 3,
  },
  {
    key: "onboarding_first_post",
    name: "Contributor",
    description: "Create your first post",
    icon: "✏️",
    type: "onboarding",
    xpReward: 50,
    criteria: { action: "post:create", count: 1 },
    repeatable: false,
    sortOrder: 4,
  },
  {
    key: "onboarding_first_comment",
    name: "Join the Discussion",
    description: "Write your first comment",
    icon: "💬",
    type: "onboarding",
    xpReward: 25,
    criteria: { action: "thread:create", count: 1 },
    repeatable: false,
    sortOrder: 5,
  },

  // Daily quests (repeatable)
  {
    key: "daily_login",
    name: "Check In",
    description: "Log in today",
    icon: "☀️",
    type: "daily",
    xpReward: 10,
    criteria: { action: "daily:login", count: 1 },
    repeatable: true,
    sortOrder: 10,
  },
  {
    key: "daily_shout",
    name: "Social Butterfly",
    description: "Send 3 shouts today",
    icon: "🦋",
    type: "daily",
    xpReward: 15,
    criteria: { action: "shout:create", count: 3 },
    repeatable: true,
    sortOrder: 11,
  },
  {
    key: "daily_engage",
    name: "Active Voice",
    description: "Create a post or comment",
    icon: "🎤",
    type: "daily",
    xpReward: 20,
    criteria: { action: "thread:create", count: 1 },
    repeatable: true,
    sortOrder: 12,
  },

  // Weekly quests (repeatable)
  {
    key: "weekly_posts",
    name: "Content Creator",
    description: "Create 3 posts this week",
    icon: "📝",
    type: "weekly",
    xpReward: 75,
    criteria: { action: "post:create", count: 3 },
    repeatable: true,
    sortOrder: 20,
  },
  {
    key: "weekly_comments",
    name: "Community Pillar",
    description: "Write 10 comments this week",
    icon: "🏛️",
    type: "weekly",
    xpReward: 50,
    criteria: { action: "thread:create", count: 10 },
    repeatable: true,
    sortOrder: 21,
  },
  {
    key: "weekly_event",
    name: "Event Planner",
    description: "Create a calendar event",
    icon: "📅",
    type: "weekly",
    xpReward: 30,
    criteria: { action: "event:create", count: 1 },
    repeatable: true,
    sortOrder: 22,
  },

  // Tutorial quests (one-time)
  {
    key: "tutorial_tier1",
    name: "Getting Started",
    description: "Complete all Tier 1 tutorial steps (set alias, survey, report issue)",
    icon: "🎓",
    type: "onboarding",
    xpReward: 50,
    criteria: { action: "tour:tier", count: 1 },
    repeatable: false,
    sortOrder: 30,
  },
  {
    key: "tutorial_tier2",
    name: "Community Explorer",
    description: "Complete all Tier 2 tutorial steps (boards, posts, gamification)",
    icon: "🧭",
    type: "onboarding",
    xpReward: 100,
    criteria: { action: "tour:tier", count: 1 },
    repeatable: false,
    sortOrder: 31,
  },
  {
    key: "tutorial_tier3",
    name: "Admin Basics",
    description: "Complete all Tier 3 admin tutorial steps",
    icon: "⚙️",
    type: "onboarding",
    xpReward: 75,
    criteria: { action: "tour:tier", count: 1 },
    repeatable: false,
    sortOrder: 32,
  },
  {
    key: "tutorial_tier4",
    name: "Team Leader",
    description: "Complete all Tier 4 management tutorial steps",
    icon: "👑",
    type: "onboarding",
    xpReward: 75,
    criteria: { action: "tour:tier", count: 1 },
    repeatable: false,
    sortOrder: 33,
  },
];
