export const INITIAL_ACHIEVEMENTS = [
  // Onboarding
  {
    key: "welcome",
    name: "Welcome!",
    description: "Set your alias for the first time",
    icon: "👋",
    tier: null,
    category: "onboarding",
    xpReward: 25,
    criteria: { type: "count", action: "alias:set", threshold: 1 },
    sortOrder: 1,
  },
  {
    key: "surveyor",
    name: "Have Your Say",
    description: "Complete the community survey",
    icon: "📋",
    tier: null,
    category: "onboarding",
    xpReward: 50,
    criteria: { type: "count", action: "survey:complete", threshold: 1 },
    sortOrder: 2,
  },

  // Social — Shouts (tiered)
  {
    key: "shouter_bronze",
    name: "Loud & Proud",
    description: "Send 25 shouts",
    icon: "📢",
    tier: "bronze",
    category: "social",
    xpReward: 50,
    criteria: { type: "count", action: "shout:create", threshold: 25 },
    sortOrder: 30,
  },
  {
    key: "shouter_silver",
    name: "Town Crier",
    description: "Send 100 shouts",
    icon: "📢",
    tier: "silver",
    category: "social",
    xpReward: 100,
    criteria: { type: "count", action: "shout:create", threshold: 100 },
    sortOrder: 31,
  },
  {
    key: "shouter_gold",
    name: "Megaphone",
    description: "Send 500 shouts",
    icon: "📢",
    tier: "gold",
    category: "social",
    xpReward: 250,
    criteria: { type: "count", action: "shout:create", threshold: 500 },
    sortOrder: 32,
  },

  // Moderation
  {
    key: "bug_hunter_bronze",
    name: "Bug Hunter",
    description: "Report your first issue",
    icon: "🐛",
    tier: "bronze",
    category: "moderation",
    xpReward: 30,
    criteria: { type: "count", action: "issue:create", threshold: 1 },
    sortOrder: 40,
  },
  {
    key: "bug_hunter_silver",
    name: "Quality Guardian",
    description: "Report 5 issues",
    icon: "🐛",
    tier: "silver",
    category: "moderation",
    xpReward: 75,
    criteria: { type: "count", action: "issue:create", threshold: 5 },
    sortOrder: 41,
  },
  {
    key: "bug_hunter_gold",
    name: "Bug Exterminator",
    description: "Report 15 issues",
    icon: "🐛",
    tier: "gold",
    category: "moderation",
    xpReward: 150,
    criteria: { type: "count", action: "issue:create", threshold: 15 },
    sortOrder: 42,
  },

  // Streak achievements
  {
    key: "streak_bronze",
    name: "Dedicated",
    description: "7-day login streak",
    icon: "🔥",
    tier: "bronze",
    category: "social",
    xpReward: 75,
    criteria: { type: "count", action: "login:streak", threshold: 7 },
    sortOrder: 70,
  },
  {
    key: "streak_silver",
    name: "Committed",
    description: "30-day login streak",
    icon: "🔥",
    tier: "silver",
    category: "social",
    xpReward: 200,
    criteria: { type: "count", action: "login:streak", threshold: 30 },
    sortOrder: 71,
  },
  {
    key: "streak_gold",
    name: "Unstoppable",
    description: "90-day login streak",
    icon: "🔥",
    tier: "gold",
    category: "social",
    xpReward: 500,
    criteria: { type: "count", action: "login:streak", threshold: 90 },
    sortOrder: 72,
  },
  {
    key: "streak_legendary",
    name: "Eternal Flame",
    description: "365-day login streak",
    icon: "🔥",
    tier: "legendary",
    category: "social",
    xpReward: 1000,
    criteria: { type: "count", action: "login:streak", threshold: 365 },
    sortOrder: 73,
  },

  // Feedback achievements
  {
    key: "feedback_first",
    name: "Heard!",
    description: "Submit your first feedback",
    icon: "💡",
    tier: null,
    category: "onboarding",
    xpReward: 25,
    criteria: { type: "count", action: "feedback:submit", threshold: 1 },
    sortOrder: 5,
  },

  // Tutorial achievements
  {
    key: "quick_learner",
    name: "Quick Learner",
    description: "Complete all tutorial steps available for your role",
    icon: "🎓",
    tier: null,
    category: "onboarding",
    xpReward: 100,
    criteria: { type: "count", action: "tour:step", threshold: 10 },
    sortOrder: 80,
  },
  {
    key: "tour_guide",
    name: "Tour Guide",
    description: "Complete all 17 tutorial steps",
    icon: "🗺️",
    tier: "legendary",
    category: "onboarding",
    xpReward: 500,
    criteria: { type: "count", action: "tour:step", threshold: 17 },
    sortOrder: 81,
  },
  {
    key: "demo_explorer",
    name: "Demo Explorer",
    description: "Complete the guided demo tutorial",
    icon: "🧪",
    tier: "bronze",
    category: "onboarding",
    xpReward: 75,
    criteria: { type: "count", action: "tour:complete", threshold: 1 },
    sortOrder: 82,
  },
];

export const INITIAL_QUESTS = [
  // Onboarding (one-time)
  {
    key: "onboarding_alias",
    name: "Identity Crisis",
    description: "Set your community alias",
    icon: "🏷️",
    type: "onboarding",
    xpReward: 25,
    criteria: { action: "alias:set", count: 1 },
    repeatable: false,
    sortOrder: 1,
    priority: "normal",
    status: "active",
  },
  {
    key: "onboarding_survey",
    name: "Have Your Say",
    description: "Complete the community survey",
    icon: "📋",
    type: "onboarding",
    xpReward: 100,
    criteria: { action: "survey:complete", count: 1 },
    repeatable: false,
    sortOrder: 2,
    priority: "normal",
    status: "active",
  },
  {
    key: "onboarding_first_shout",
    name: "First Words",
    description: "Send your first shout",
    icon: "📢",
    type: "onboarding",
    xpReward: 25,
    criteria: { action: "shout:create", count: 1 },
    repeatable: false,
    sortOrder: 3,
    priority: "normal",
    status: "active",
  },
  // Daily quests (repeatable)
  {
    key: "daily_login",
    name: "Check In",
    description: "Log in today",
    icon: "☀️",
    type: "daily",
    xpReward: 10,
    criteria: { action: "daily:login", count: 1 },
    repeatable: true,
    sortOrder: 10,
    priority: "normal",
    status: "active",
  },
  {
    key: "daily_shout",
    name: "Social Butterfly",
    description: "Send 3 shouts today",
    icon: "🦋",
    type: "daily",
    xpReward: 15,
    criteria: { action: "shout:create", count: 3 },
    repeatable: true,
    sortOrder: 11,
    priority: "normal",
    status: "active",
  },
];
